name: build-and-push
on:
  push:
    branches:
      - main
    workflow_dispatch: {}

permissions:
  contents: read

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - name: Setup QEMU
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3.0.0
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ghcr.io
          username: chanwit
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: distroless/actions/apko-publish@main
        with:
          config: postgres-15.4.yaml
          tag: ghcr.io/llm-gitops/postgres:15.4
      - name: Fetch pgvector
        run: |
          git clone https://github.com/pgvector/pgvector
          cp Dockerfile pgvector/Dockerfile
      - name: Publish images
        id: build-push
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          push: true
          builder: ${{ steps.buildx.outputs.name }}
          context: ./pgvector
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/llm-gitops/vectors:v1.0.0
